In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import glob 
import os

m_store = pd.read_csv('m_store.csv')
m_area = pd.read_csv('m_area.csv')

current_dir = os.getcwd()
tbl_order_file = os.path.join(current_dir, 'tbl_order_*.csv')
tbl_order_files = glob.glob(tbl_order_file)

order_all = pd.DataFrame()
for file in tbl_order_files:
    order_tmp = pd.read_csv(file)
    print(f'{file}: {len(order_tmp)}')
    order_all = pd.concat([order_all, order_tmp], ignore_index = True)
    
order_all = order_all.loc[order_all['store_id'] != 999]

order_all = pd.merge(order_all, m_store, on='store_id', how='left')
order_all = pd.merge(order_all, m_area, on='area_cd', how='left')

order_all.loc[order_all['takeout_flag'] == 0, 'takeout_name'] = 'デリバリー'
order_all.loc[order_all['takeout_flag'] == 1, 'takeout_name'] = 'お持ち帰り'

order_all.loc[order_all['status'] == 0, 'status_name'] = '受付'
order_all.loc[order_all['status'] == 1, 'status_name'] = 'お支払い済み'
order_all.loc[order_all['status'] == 2, 'status_name'] = 'お渡し済み'
order_all.loc[order_all['status'] == 9, 'status_name'] = 'キャンセル'

order_all.loc[:, 'order_date'] = pd.to_datetime(order_all['order_accept_date']).dt.date

order_all.head()

/Users/yuto/Desktop/Machine-learning-100/ch4/tbl_order_202006.csv: 233301
/Users/yuto/Desktop/Machine-learning-100/ch4/tbl_order_202004.csv: 233260
/Users/yuto/Desktop/Machine-learning-100/ch4/tbl_order_202005.csv: 241139

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status,store_name,area_cd,wide_area,narrow_area,takeout_name,status_name,order_date
0,16514392,64,C44271355,49,56527968,2020-06-01 11:00:00,2020-06-01 11:55:00,0,2732,2,西東京店,TK,東京,東京,デリバリー,お渡し済み,2020-06-01
1,28342394,12,C98307866,98,46924304,2020-06-01 11:00:00,2020-06-01 11:52:00,0,2064,2,西葛西店,TK,東京,東京,デリバリー,お渡し済み,2020-06-01
2,29799587,174,C59484037,45,47054474,2020-06-01 11:00:00,2020-06-01 11:25:00,0,3900,2,新座店,SA,埼玉,埼玉,デリバリー,お渡し済み,2020-06-01
3,96960753,23,C57278332,70,60848267,2020-06-01 11:00:00,2020-06-01 11:45:00,0,2750,2,江東店,TK,東京,東京,デリバリー,お渡し済み,2020-06-01
4,52147209,7,C36890849,80,20633593,2020-06-01 11:00:00,2020-06-01 11:23:00,0,2328,2,東尾久店,TK,東京,東京,デリバリー,お渡し済み,2020-06-01

In [3]:
import openpyxl

wb = openpyxl.Workbook()
ws = wb['Sheet']
ws.cell(1, 1).value = '書き込みテストです。'
wb.save('test.xlsx')
wb.close()

In [4]:
wb = openpyxl.load_workbook('test.xlsx', read_only=True)
ws = wb['Sheet']
print(ws.cell(1, 1).value)
wb.close()

書き込みテストです。

In [5]:
store_id = 1

store_df = order_all.loc[order_all['store_id'] == store_id].copy()

store_name = store_df['store_name'].unique()[0]
store_sales_total = store_df.loc[store_df['status'].isin([1, 2])]['total_amount'].sum()
store_sales_takeout = store_df.loc[store_df['status'] == 1]['total_amount'].sum()
store_sales_delivery = store_df.loc[store_df['status'] == 2]['total_amount'].sum()

print(f'売り上げ確認 {store_sales_total} = {store_sales_takeout + store_sales_delivery}')
output_df = store_df[['order_accept_date', 'customer_id','total_amount', 'takeout_name', 'status_name']]
output_df.head()

売り上げ確認 9004535 = 9004535

        order_accept_date customer_id  total_amount takeout_name status_name
58    2020-06-01 11:05:05   C13019060          3530        デリバリー       お渡し済み
222   2020-06-01 11:16:16   C42292941          3617        デリバリー       お渡し済み
309   2020-06-01 11:24:24   C04466742          2877        お持ち帰り      お支払い済み
641   2020-06-01 11:52:52   C05244872          2987        お持ち帰り      お支払い済み
1118  2020-06-01 12:31:31   C27811735          1882        お持ち帰り      お支払い済み

In [6]:
from openpyxl.utils.dataframe import dataframe_to_rows

store_title = f'{store_id}_{store_name}'

wb = openpyxl.Workbook()
ws = wb.active
ws.title = store_title

ws.cell(1, 1).value = f'{store_title} 売り上げデータ'

rows = dataframe_to_rows(output_df, index=False)

row_start = 3
col_start = 2

for row_no, row in enumerate(rows, row_start):
    for col_no, value in enumerate(row, col_start):
        ws.cell(row_no, col_no).value = value
        
filename = f'{store_title}.xlsx'
wb.save(filename)
wb.close()

# Excelの表を整えて出力してみよう

In [7]:
from openpyxl.styles import PatternFill, Border, Side, Font

wb = openpyxl.load_workbook(filename)
ws = wb[store_title]

side = Side(style='thin', color='008000')
border = Border(top=side, bottom=side, left=side, right=side)

for row in ws:
    for cell in row:
        if ws[cell.coordinate].value:
            ws[cell.coordinate].border = border

ws.cell(1, 1).font = Font(bold=True, color='008000')
            
cell = ws.cell(3, 2)
cell.fill = PatternFill(patternType='solid', fgColor='008000')
cell.value = '注文受注日時'
cell.font = Font(bold=True, color='FFFFFF')

cell = ws.cell(3, 3)
cell.fill = PatternFill(patternType='solid', fgColor='008000')
cell.value = '顧客ID'
cell.font = Font(bold=True, color='FFFFFF')

cell = ws.cell(3, 4)
cell.fill = PatternFill(patternType='solid', fgColor='008000')
cell.value = '購入総額'
cell.font = Font(bold=True, color='FFFFFF')

cell = ws.cell(3, 5)
cell.fill = PatternFill(patternType='solid', fgColor='008000')
cell.value = '注文タイプ'
cell.font = Font(bold=True, color='FFFFFF')

cell = ws.cell(3, 6)
cell.fill = PatternFill(patternType='solid', fgColor='008000')
cell.value = '注文状態'
cell.font = Font(bold=True, color='FFFFFF')

ws.column_dimensions['A'].width = 20
ws.column_dimensions['B'].width = 20
ws.column_dimensions['C'].width = 12
ws.column_dimensions['D'].width = 12
ws.column_dimensions['E'].width = 12
ws.column_dimensions['F'].width = 12

wb.save(filename)
wb.close()

# 33.売り上げ以外のデータも出力してみよう

In [8]:
def calc_delta(t):
    t1, t2 = t
    delta = t2 - t1
    return delta.total_seconds() / 60

store_df.loc[:, 'order_accept_datetime'] = pd.to_datetime(store_df['order_accept_date'])
store_df.loc[:, 'delivered_datetime'] = pd.to_datetime(store_df['delivered_date'])
store_df.loc[:, 'delta'] = store_df[['order_accept_datetime', 'delivered_datetime']].apply(calc_delta, axis=1)

delivery_time = store_df.groupby('store_id')['delta'].describe()
delivery_time

           count       mean        std   min   25%   50%   75%   max
store_id
1         3553.0  34.477062  14.514403  10.0  22.0  34.0  47.0  59.0

In [9]:
wb = openpyxl.load_workbook(filename)
ws = wb[store_title]

cell = ws.cell(1, 7)
cell.value = f'配達完了までの時間:'
cell.font = Font(bold=True, color='008080')

rows = dataframe_to_rows(delivery_time, index=False)

row_start = 3
col_start = 8

for row_no, row in enumerate(rows, row_start):
    for col_no, value in enumerate(row, col_start):
        cell = ws.cell(row_no, col_no)
        cell.value = value
        cell.border = border
        if row_no == row_start:
            cell.fill = PatternFill(patternType='solid', fgColor='008000')
            cell.font = Font(bold=True, color='FFFFFF')
            
filename = f'{store_title}.xlsx'
wb.save(filename)
wb.close()

# 34.問題のある箇所を赤字で出力してみよう

In [10]:
filename = f'{store_title}.xlsx'

openpyxl.load_workbook(filename)
ws = wb[store_title]

rows = dataframe_to_rows(output_df, index=False, header=True)

row_start = 3
col_start = 2

for row_no, row in enumerate(rows, row_start):
    if row_no == row_start:
        continue
    for col_no, value in enumerate(row, col_start):
        ws.cell(row_no, col_no).value = value
        if value == 'キャンセル':
            ws.cell(row_no, col_no).font = Font(bold=True, color='FF0000')
            
filename = f'{store_title}.xlsx'
wb.save(filename)
wb.close()

# 36.エクセルのセル関数で日毎の集計をしてみよう

In [11]:
filename = f'{store_title}.xlsx'

openpyxl.load_workbook(filename)
ws = wb[store_title]

cell = ws.cell(7, 7)
cell.value = '集計'
cell.font = Font(bold=True, color='008080')

cell = ws.cell(8, 8)
cell.value = 'データ総額'
cell.font = Font(bold=True, color='008080')

cell = ws.cell(8, 10)
cell.value = f'=SUM(D4:D{ws.max_row})'

cell = ws.cell(9, 8)
cell.value = '　内　決算額'
cell.font = Font(bold=True)

cell = ws.cell(9, 10)
cell.value = f'=SUMIF(F4:F{ws.max_row}, "<>キャンセル", D4:D{ws.max_row})'

cell = ws.cell(10, 8)
cell.value = '　内　キャンセル'
cell.font = Font(bold=True)

cell = ws.cell(10, 10)
cell.value = f'=SUMIF(F4:F{ws.max_row}, "=キャンセル", D4:D{ws.max_row})'

filename = f'{store_title}.xlsx'
wb.save(filename)
wb.close()

# 36.折れ線グラフにして出力してみよう

In [12]:
from openpyxl.chart import Reference, BarChart, PieChart, LineChart, ScatterChart, Series

openpyxl.load_workbook(filename)
ws = wb[store_title]

cell = ws.cell(7, 7)
cell.value = f'売り上げグラフ'
cell.font = Font(bold=True, color='008080')

refy = Reference(ws, min_col=4, min_row=4, max_col=4, max_row=23)

series = Series(refy, title='売り上げ額')

chart = LineChart()
chart.title = '折れ線グラフ'
chart.x_axis.title = '件数'
chart.y_axis.title = '売上額'
chart.height = 10
chart.width = 20
chart.series.append(series)

ws.add_chart(chart, 'H12')

filename = f'{store_title}.xlsx'
wb.save(filename)
wb.close()

# 37.レポートに向けてデータを準備しよう

In [13]:
cancel_df = pd.DataFrame()

cancel_cnt = order_all.loc[order_all['status'] == 9].groupby('store_id')['store_id'].count()
order_cnt = order_all.loc[order_all['status'].isin([1, 2, 9])].groupby('store_id')['store_id'].count()
cancel_rate = cancel_cnt / order_cnt * 100

cancel_df['cancel_rate'] = cancel_rate

cancel_df = pd.merge(cancel_df, m_store, on='store_id', how='left')
cancel_rank = cancel_df.sort_values(['cancel_rate']).reset_index()

In [14]:
def check_store_cancel_rank(trg_id):
    tmp = cancel_rank.loc[cancel_rank['store_id'] == trg_id].index[0] + 1
    return tmp

In [15]:
def get_area_df(trg_id):
    '''
    該当店舗が属する地域別データの集計と売上ランク
    '''
    area_df = pd.DataFrame()
    area_df = order_all.loc[order_all['area_cd'] == store_df['area_cd'].unique()[0]]
    area_df = area_df.loc[area_df['status'].isin([1, 2])]
    
    return area_df


def get_area_rank_df(trg_id):
    area_df = get_area_df(trg_id)
    area_rank = area_df.groupby('store_id')['total_amount'].sum().sort_values(ascending=False)
    area_rank = pd.merge(area_rank, m_store, on='store_id', how='left')
    
    return area_rank

def check_store_sales_rank(trg_id):
    area_rank = get_area_rank_df(trg_id)
    tmp = area_rank.loc[area_rank['store_id']==trg_id].index[0] + 1
    
    return tmp

In [16]:
def make_store_daily(trg_id):
    tmp_store_df = order_all.loc[(order_all['store_id'] == trg_id) & (order_all['status'].isin([1, 2]))]
    tmp = tmp_store_df[['order_accept_date', 'total_amount']].copy()
    tmp.loc[:, 'order_accept_date'] = pd.to_datetime(tmp['order_accept_date'])
    tmp.set_index('order_accept_date', inplace=True)
    tmp = tmp.resample('D').sum().reset_index()
    
    return tmp

In [22]:
def get_area_delivery(trg_id):
    '''
    該当店舗が属する地域別データの配達完了までの時間ランク
    '''
    area_delivery = pd.DataFrame()
    area_df = get_area_df(trg_id)
    area_delivery = area_df.loc[area_df['status']==2].copy()
    
    area_delivery.loc[:, 'order_accept_datetime'] = pd.to_datetime(area_delivery['order_accept_date'])
    area_delivery.loc[:, 'delivered_datetime'] = pd.to_datetime(area_delivery['delivered_date'])
    area_delivery.loc[:, 'delta'] = area_delivery[['order_accept_datetime', 'delivered_datetime']].apply(calc_delta, axis=1)
    
    return area_delivery


def get_area_delivery_rank_df(trg_id):
    area_delivery = get_area_delivery(trg_id)
    area_delivery_rank = area_delivery.groupby('store_id')['delta'].mean().sort_values()
    area_delivery_rank = pd.merge(area_delivery_rank, m_store, on='store_id', how='left')
    
    return area_delivery_rank


def check_store_delivery_rank(trg_id):
    area_delivery_rank = get_area_delivery_rank_df(trg_id)
    tmp = area_delivery_rank.loc[area_delivery_rank['store_id'] == trg_id].index[0] + 1
    
    return tmp

# 38.データシート必要なデータを出力しよう

In [18]:
if os.path.exists('test.xlsx'):
    os.remove('test.xlsx')
if os.path.exists(filename):
    os.remove(filename)

In [39]:
def data_sheet_output(trg_wb, sheetname, target_df, indexFlg):
    ws = trg_wb.create_sheet(title=sheetname)
    
    rows = dataframe_to_rows(target_df, index=indexFlg, header=True)
    
    row_start = 1
    col_start = 1
    
    for row_no, row in enumerate(rows, row_start):
        for col_no, value in enumerate(row, col_start):
            ws.cell(row_no, col_no).value = value
            
    # ws.sheet_state = 'hidden'

In [40]:
def make_data_sheet(trg_id, trg_st_df, targetfolder):
    target_daily = make_store_daily(trg_id)
    store_name = trg_st_df['store_name'].unique()[0]
    
    store_title = f'{trg_id}_{store_name}'
    
    wb = openpyxl.Workbook()
    
    # キャンセルランキング
    data_sheet_output(wb, 'Data_CancelRank', cancel_rank, False)
    
    # エリア売上ランキング
    data_sheet_output(wb, 'Data_AreaRank', get_area_rank_df(trg_id), False)
    
    # エリア配達時間ランキング
    data_sheet_output(wb, 'Data_DeliveryRank', get_area_delivery_rank_df(trg_id), False)
    
    # 該当店舗の日単位売上データ
    data_sheet_output(wb, 'Data_Target_Daily', target_daily, False)
    
    filename = os.path.join(targetfolder, f'{store_title}.xlsx')
    wb.save(filename)
    wb.close()
    
    return filename

In [41]:
filename_store = make_data_sheet(store_id, store_df, '')

# 39.サマリーシートを作成しよう

In [44]:
def make_summary_sheet(trg_id, storename, trgfile):
    target_cancel_rank = check_store_cancel_rank(trg_id)
    target_sales_rank = check_store_sales_rank(trg_id)
    target_delivery_rank = check_store_delivery_rank(trg_id)
    
    
    wb = openpyxl.load_workbook(trgfile)
    ws = wb.active
    ws.title = 'サマリーレポート'
    
    cell = ws.cell(1, 1)
    cell.value = f'{storename} サマリーレポート （4月〜６月）'
    cell.font = Font(bold=True, color='008080', size=20)
    
    
    # 売上ランキングの表示
    tmpWs = wb['Data_Target_Daily']
    cell = ws.cell(3, 2)   
    cell.value = '店舗売上額'
    cell.font = Font(bold=True, color='008080', size=16)
    
    # セルの結合
    ws.merge_cells('E3:F3')
    
    cell = ws.cell(3, 5)
    cell.value = f'=SUM({tmpWs.title}!B2:B{tmpWs.max_row})'
    cell.font = Font(bold=True, color='0080FF', size=16)
    cell.number_format = '#,##0'
    
    cell = ws.cell(4, 2)
    cell.value = '店舗売上ランク'
    cell.font = Font(bold=True, color='008080', size=16)
    
    cell = ws.cell(4, 5)
    cell.value = f'{len(m_store)} 店舗中 {target_sales_rank}位'
    cell.font = Font(bold=True, color='0080FF', size=16)
    
    
    # グラフ用の参照データを指定
    refy = Reference(tmpWs, min_col=2, min_row=2, max_col=2, max_row=tmpWs.max_row)
    
    series = Series(refy, title='売上額')
    
    chart = LineChart()
    chart.title = '期間売上額（日毎）'
    chart.x_axis.title = '件数'
    chart.y_axis.title = '売上額'
    chart.height = 10
    chart.width = 15
    chart.series.append(series)
    
    ws.add_chart(chart, 'B6')
    
    
    # 地域情報
    tmpWs = wb['Data_AreaRank']
    
    cell = ws.cell(4, 10)
    cell.value = '地域店舗売上情報'
    cell.font = Font(bold=True, color='008080', size=16)
    
    cell = ws.cell(5, 11)
    cell.value = '最高額'
    
    cell = ws.cell(5, 12)
    cell.value = f'=MAX({tmpWs.title}!B2:B{tmpWs.max_row})'
    cell.number_format = '#,##0'
    
    cell = ws.cell(6, 11)
    cell.value = '最低額'
    
    cell = ws.cell(6, 12)
    cell.value = f'=MIN({tmpWs.title}!B2:B{tmpWs.max_row})'
    cell.number_format = '#,##0'
    
    cell = ws.cell(7, 11)
    cell.value = '地域平均'
    
    cell = ws.cell(7, 12)
    cell.value = f'=AVERAGE({tmpWs.title}!B2:B{tmpWs.max_row})'
    cell.number_format = '#,##0'
    
    
    # キャンセル率の表示
    cell = ws.cell(11, 10)
    cell.value = 'キャンセルランク'
    cell.font = Font(bold=True, color='008080', size=16)
    
    cell = ws.cell(12, 11)
    cell.value = f'{len(m_store)} 店舗中 {target_cancel_rank}位'
    cell.font = Font(bold=True, color='0080FF', size=16)
    
    
    
    tmpWs = wb['Data_CancelRank']
    
    cell = ws.cell(13, 11)
    cell.value = '地域平均'
    
    cell = ws.cell(13, 12)
    cell.value = f'=AVERAGE({tmpWs.title}!C2:C{tmpWs.max_row})'
    cell.number_format = '0.00'
    
    # 配達時間ランキングの表示
    cell = ws.cell(15, 10)
    cell.value = '配達時間ランキング'
    cell.font = Font(bold=True, color='008080', size=16)
    
    cell = ws.cell(16, 11)
    cell.value = f'{len(m_store)} 店舗中 {target_delivery_rank}位'
    cell.font = Font(bold=True, color='0080FF', size=16)
    
    
    tmpWs = wb['Data_DeliveryRank']
    
    cell = ws.cell(17, 11)
    cell.value = '地域平均'
    
    cell = ws.cell(17, 12)
    cell.value = f'=AVERAGE({tmpWs.title}!B2:B{tmpWs.max_row})'
    cell.number_format = '0.00'
    
    wb.save(trgfile)
    wb.close()

In [45]:
make_summary_sheet(store_id, store_name, filename_store)

# 40.店舗別にレポートをExcel出力してみよう

In [48]:
os.makedirs('output', exist_ok=True)

for store in m_store['store_id'].tolist():
    if store != 999:
        store_df = order_all.loc[order_all['store_id'] == store]
        store_name = m_store.loc[m_store['store_id'] == store]['store_name']
        print(store_name)
        
        tmp_file_name = make_data_sheet(store, store_df, 'output')
        make_summary_sheet(store, store_name.values[0], tmp_file_name)
        
print('出力完了しました。')

0    昭島店
Name: store_name, dtype: object
1    あきる野店
Name: store_name, dtype: object
2    足立店
Name: store_name, dtype: object
3    北千住店
Name: store_name, dtype: object
4    綾瀬店
Name: store_name, dtype: object
5    荒川店
Name: store_name, dtype: object
6    東尾久店
Name: store_name, dtype: object
7    板橋店
Name: store_name, dtype: object
8    高島平店
Name: store_name, dtype: object
9    稲城店
Name: store_name, dtype: object
10    江戸川店
Name: store_name, dtype: object
11    西葛西店
Name: store_name, dtype: object
12    青梅店
Name: store_name, dtype: object
13    大田店
Name: store_name, dtype: object
14    大森店
Name: store_name, dtype: object
15    蒲田店
Name: store_name, dtype: object
16    葛飾店
Name: store_name, dtype: object
17    亀有店
Name: store_name, dtype: object
18    赤羽店
Name: store_name, dtype: object
19    王子店
Name: store_name, dtype: object
20    清瀬店
Name: store_name, dtype: object
21    国立店
Name: store_name, dtype: object
22    江東店
Name: store_name, dtype: object
23    富岡店
Name: store_name, dtype: object
24    南砂店
Name: store_name, dtype: object
25    小金井店
Name: store_name, dtype: object
26    国分寺店
Name: store_name, dtype: object
27    小平店
Name: store_name, dtype: object
28    狛江店
Name: store_name, dtype: object
29    品川店
Name: store_name, dtype: object
30    五反田店
Name: store_name, dtype: object
31    大井店
Name: store_name, dtype: object
32    渋谷店
Name: store_name, dtype: object
33    恵比寿店
Name: store_name, dtype: object
34    代々木店
Name: store_name, dtype: object
35    新宿店
Name: store_name, dtype: object
36    大久保店
Name: store_name, dtype: object
37    高田馬場店
Name: store_name, dtype: object
38    杉並店
Name: store_name, dtype: object
39    高円寺店
Name: store_name, dtype: object
40    荻窪店
Name: store_name, dtype: object
41    墨田店
Name: store_name, dtype: object
42    向島店
Name: store_name, dtype: object
43    世田谷店
Name: store_name, dtype: object
44    池尻店
Name: store_name, dtype: object
45    駒沢店
Name: store_name, dtype: object
46    成城店
Name: store_name, dtype: object
47    上野店
Name: store_name, dtype: object
48    浅草店
Name: store_name, dtype: object
49    谷中店
Name: store_name, dtype: object
50    立川店
Name: store_name, dtype: object
51    多摩店
Name: store_name, dtype: object
52    銀座店
Name: store_name, dtype: object
53    日本橋店
Name: store_name, dtype: object
54    調布店
Name: store_name, dtype: object
55    神田店
Name: store_name, dtype: object
56    九段店
Name: store_name, dtype: object
57    池袋店
Name: store_name, dtype: object
58    巣鴨店
Name: store_name, dtype: object
59    駒込店
Name: store_name, dtype: object
60    中野店
Name: store_name, dtype: object
61    東中野店
Name: store_name, dtype: object
62    西多摩店
Name: store_name, dtype: object
63    西東京店
Name: store_name, dtype: object
64    練馬店
Name: store_name, dtype: object
65    石神井店
Name: store_name, dtype: object
66    大泉店
Name: store_name, dtype: object
67    八王子店
Name: store_name, dtype: object
68    羽村店
Name: store_name, dtype: object
69    東久留米店
Name: store_name, dtype: object
70    東村山店
Name: store_name, dtype: object
71    東大和店
Name: store_name, dtype: object
72    日野店
Name: store_name, dtype: object
73    府中店
Name: store_name, dtype: object
74    福生店
Name: store_name, dtype: object
75    本郷店
Name: store_name, dtype: object
76    大塚店
Name: store_name, dtype: object
77    町田店
Name: store_name, dtype: object
78    三鷹店
Name: store_name, dtype: object
79    赤坂店
Name: store_name, dtype: object
80    青山店
Name: store_name, dtype: object
81    六本木店
Name: store_name, dtype: object
82    武蔵野店
Name: store_name, dtype: object
83    武蔵村山店
Name: store_name, dtype: object
84    目黒店
Name: store_name, dtype: object
85    自由が丘店
Name: store_name, dtype: object
86    愛甲店
Name: store_name, dtype: object
87    足柄上店
Name: store_name, dtype: object
88    厚木店
Name: store_name, dtype: object
89    綾瀬店
Name: store_name, dtype: object
90    伊勢原店
Name: store_name, dtype: object
91    海老名店
Name: store_name, dtype: object
92    小田原店
Name: store_name, dtype: object
93    鎌倉店
Name: store_name, dtype: object
94    麻生店
Name: store_name, dtype: object
95    川崎店
Name: store_name, dtype: object
96    幸店
Name: store_name, dtype: object
97    高津店
Name: store_name, dtype: object
98    川崎多摩店
Name: store_name, dtype: object
99    中原店
Name: store_name, dtype: object
100    宮前店
Name: store_name, dtype: object
101    高座店
Name: store_name, dtype: object
102    相模原店
Name: store_name, dtype: object
103    座間店
Name: store_name, dtype: object
104    逗子店
Name: store_name, dtype: object
105    茅ヶ崎店
Name: store_name, dtype: object
106    中店
Name: store_name, dtype: object
107    秦野店
Name: store_name, dtype: object
108    平塚店
Name: store_name, dtype: object
109    藤沢店
Name: store_name, dtype: object
110    三浦店
Name: store_name, dtype: object
111    南足柄店
Name: store_name, dtype: object
112    大和店
Name: store_name, dtype: object
113    横須賀店
Name: store_name, dtype: object
114    青葉店
Name: store_name, dtype: object
115    旭店
Name: store_name, dtype: object
116    泉店
Name: store_name, dtype: object
117    磯子店
Name: store_name, dtype: object
118    神奈川店
Name: store_name, dtype: object
119    金沢店
Name: store_name, dtype: object
120    港南店
Name: store_name, dtype: object
121    港北店
Name: store_name, dtype: object
122    栄店
Name: store_name, dtype: object
123    瀬谷店
Name: store_name, dtype: object
124    都筑店
Name: store_name, dtype: object
125    鶴見店
Name: store_name, dtype: object
126    戸塚店
Name: store_name, dtype: object
127    保土ケ谷店
Name: store_name, dtype: object
128    横浜緑店
Name: store_name, dtype: object
129    横浜南店
Name: store_name, dtype: object
130    我孫子店
Name: store_name, dtype: object
131    市川店
Name: store_name, dtype: object
132    市原店
Name: store_name, dtype: object
133    浦安店
Name: store_name, dtype: object
134    柏店
Name: store_name, dtype: object
135    木更津店
Name: store_name, dtype: object
136    君津店
Name: store_name, dtype: object
137    佐倉店
Name: store_name, dtype: object
138    白井店
Name: store_name, dtype: object
139    千葉中央店
Name: store_name, dtype: object
140    千葉緑店
Name: store_name, dtype: object
141    若葉店
Name: store_name, dtype: object
142    富里店
Name: store_name, dtype: object
143    流山店
Name: store_name, dtype: object
144    習志野店
Name: store_name, dtype: object
145    成田店
Name: store_name, dtype: object
146    富津店
Name: store_name, dtype: object
147    船橋店
Name: store_name, dtype: object
148    松戸店
Name: store_name, dtype: object
149    茂原店
Name: store_name, dtype: object
150    八千代店
Name: store_name, dtype: object
151    四街道店
Name: store_name, dtype: object
152    上尾店
Name: store_name, dtype: object
153    入間店
Name: store_name, dtype: object
154    春日部店
Name: store_name, dtype: object
155    川口店
Name: store_name, dtype: object
156    川越店
Name: store_name, dtype: object
157    行田店
Name: store_name, dtype: object
158    久喜店
Name: store_name, dtype: object
159    熊谷店
Name: store_name, dtype: object
160    鴻巣店
Name: store_name, dtype: object
161    越谷店
Name: store_name, dtype: object
162    浦和店
Name: store_name, dtype: object
163    大宮店
Name: store_name, dtype: object
164    さいたま西店
Name: store_name, dtype: object
165    さいたま緑店
Name: store_name, dtype: object
166    さいたま南店
Name: store_name, dtype: object
167    坂戸店
Name: store_name, dtype: object
168    狭山店
Name: store_name, dtype: object
169    志木店
Name: store_name, dtype: object
170    草加店
Name: store_name, dtype: object
171    所沢店
Name: store_name, dtype: object
172    戸田店
Name: store_name, dtype: object
173    新座店
Name: store_name, dtype: object
174    羽生店
Name: store_name, dtype: object
175    東松山店
Name: store_name, dtype: object
176    本庄店
Name: store_name, dtype: object
177    八潮店
Name: store_name, dtype: object
178    和光店
Name: store_name, dtype: object
179    つくば店
Name: store_name, dtype: object
180    取手店
Name: store_name, dtype: object
181    那珂店
Name: store_name, dtype: object
182    日立店
Name: store_name, dtype: object
183    水戸店
Name: store_name, dtype: object
184    守谷店
Name: store_name, dtype: object
185    足利店
Name: store_name, dtype: object
186    宇都宮店
Name: store_name, dtype: object
187    小山店
Name: store_name, dtype: object
188    佐野店
Name: store_name, dtype: object
189    栃木店
Name: store_name, dtype: object
190    伊勢崎店
Name: store_name, dtype: object
191    太田店
Name: store_name, dtype: object
192    桐生店
Name: store_name, dtype: object
193    高崎店
Name: store_name, dtype: object
194    館林店
Name: store_name, dtype: object
195    前橋店
Name: store_name, dtype: object
出力完了しました。